[package]
name = "omenix"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = "0.18.2"
image = "0.25.6"
tray-icon = "0.21.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = "0.2"
glob = "0.3.2"
libc = "0.2"
